const data = [
  {
    id: 1,
    name: "Guion sobre Periféricos e Interfaces",
    contenido: [
      "En este video voy a analizar cómo interactúan los periféricos con el procesador basándome en la arquitectura de buses moderna.",
      "Casi siempre pensamos que la velocidad de una computadora depende solo del procesador, pero los periféricos son el eslabón más vital y a la vez el más lento del sistema.",
      "La razón es física: el CPU opera en nanosegundos, mientras que los periféricos trabajan a velocidades mecánicas o humanas, medidas en milisegundos.",
      "Para evitar que el procesador pase el 99% de su tiempo esperando respuestas de dispositivos lentos, la arquitectura utiliza el PCH o Platform Controller Hub.",
      "Este componente actúa como un gestor de tráfico que recoge los datos de los periféricos, los empaqueta y se los entrega ordenados al procesador.",
      "Tomemos como ejemplo el teclado y el escáner. El teclado traduce pulsaciones en pequeños códigos binarios de escaneo mediante el protocolo HID por USB.",
      "El escáner, en cambio, maneja volúmenes masivos de datos para digitalizar imágenes y suele usar protocolos como TWAIN para la transferencia.",
      "En cuanto a la salida, el monitor es el más exigente, conectándose por HDMI o DisplayPort directamente a la gráfica mediante buses PCIe de alta velocidad.",
      "La impresora, por otro lado, utiliza lenguajes como PostScript y reporta constantemente su estado, como niveles de tinta o atascos de papel.",
      "Todo este diseño se sostiene bajo tres ideas: la jerarquía de velocidad, el mecanismo de interrupciones para no saturar al CPU, y la prevención de cuellos de botella.",
      "En conclusión, la eficiencia de una computadora no reside solo en la fuerza bruta, sino en la inteligencia con la que se comunica con el mundo exterior.",
    ],
  },
  {
    id: 2,
    name: "Guion sobre Jerarquía de Memorias",
    contenido: [
      "En este video voy a explicar en detalle la jerarquía de memorias en un computador moderno y cómo esta organización es crítica para el rendimiento.",
      "Para analizarlo con datos reales, tomemos como referencia el procesador Intel Core i9-14900K, un chip donde la memoria no es un solo bloque, sino una pirámide compleja.",
      "El nivel más alto y rápido es la caché L1. Es extremadamente pequeña, apenas entre 64 y 80 KB por cada núcleo, pero su latencia es de solo 4 o 5 ciclos de reloj.",
      "Un escalón más abajo encontramos la caché L2, que en este i9 cuenta con 2 MB dedicados por cada núcleo de alto rendimiento, con una latencia de unos 12 a 15 ciclos.",
      "Luego llegamos a la caché L3, que es compartida por todos los núcleos y suma un total de 36 MB. Aquí la latencia ya sube a unos 10 o 15 nanosegundos.",
      "Finalmente, fuera del procesador, tenemos la memoria RAM DDR5 que puede llegar a 192 GB, pero cuya latencia es masiva en comparación: entre 60 y 100 nanosegundos.",
      "Para gestionar este abismo de velocidades, el procesador incluye un controlador de memoria integrado y utiliza una técnica llamada prefetching.",
      "El prefetching es esencialmente un sistema de predicción: el hardware intenta adivinar qué datos necesitarás a continuación y los trae de la RAM a la caché anticipadamente.",
      "Toda esta estructura se basa en el Principio de Localidad. Primero, la Localidad Temporal, que asume que si usaste un dato ahora, lo volverás a usar pronto.",
      "Segundo, la Localidad Espacial, que asume que si accedes a una dirección de memoria, probablemente necesites las contiguas, por lo que el sistema siempre trae bloques de 64 bytes.",
      "El diseño de esta pirámide implica trade-offs constantes. En los niveles cercanos al núcleo ganamos velocidad, pero pagamos con un alto consumo energético y generación de calor.",
      "En los niveles externos como la RAM, ganamos capacidad y menor costo, pero sacrificamos el tiempo de respuesta del sistema.",
      "En aplicaciones reales como servidores o máquinas virtuales, una caché L3 pequeña puede hacer que el bus colapse por el exceso de peticiones a la RAM.",
      "En conclusión, la jerarquía de memorias es un 'engaño' tecnológico necesario: le hace creer al procesador que tiene acceso instantáneo a gigabytes de datos.",
      "Sin esta organización estadística y física, incluso el procesador más potente del mundo se sentiría lento y torpe para el usuario final.",
    ],
  },
  {
    id: 3,
    name: "Guion sobre la ALU",
    contenido: [
      "En este video vamos a sumergirnos en el corazón matemático del procesador: la Unidad Aritmético Lógica, conocida universalmente como ALU.",
      "Si el CPU es el cerebro, la ALU es su calculadora interna, encargada de ejecutar cada suma, resta o comparación lógica que el software solicita.",
      "Para operar, la ALU utiliza registros internos denominados Registro A y Registro B, donde se cargan temporalmente los operandos antes del cálculo.",
      "La forma en que representamos los números aquí es vital. Para números enteros, utilizamos el sistema de complemento a dos, donde el bit de mayor peso indica el signo.",
      "Sin embargo, para cálculos científicos o gráficos, usamos números decimales bajo el estándar internacional IEEE 754 de coma flotante.",
      "Este estándar es fascinante porque divide un número de 32 bits en tres secciones: un bit de signo, un exponente para la escala y una mantisa para la precisión.",
      "La complejidad interna varía drásticamente según la operación. Una suma de enteros activa circuitos sencillos como el 'Full Adder' o sumador completo en un solo ciclo.",
      "Pero una multiplicación en coma flotante es como una orquesta coordinada: primero se calcula el signo con una puerta XOR, luego se suman los exponentes.",
      "Después, se multiplican las mantisas y, finalmente, se utiliza un circuito llamado 'shifter' para normalizar el resultado y ajustar el exponente final.",
      "Por ejemplo, al multiplicar 2.0 por 1.5, la ALU opera por separado la escala y la precisión para entregarnos exactamente 3.0 en formato binario.",
      "Esta complejidad técnica explica por qué las operaciones de coma flotante consumen más ciclos de reloj y mucho más calor que las operaciones enteras.",
      "Al finalizar cada cálculo, la ALU actualiza las banderas de estado o 'flags', informando si el resultado fue cero, si es un número negativo o si hubo un desbordamiento.",
      "Para un usuario, esto es invisible, pero en videojuegos o edición de video, la ALU realiza millones de estas operaciones en coma flotante por segundo.",
      "Si el diseño del multiplicador o del shifter es ineficiente, el rendimiento general del equipo caerá drásticamente, sin importar cuánta RAM tengamos.",
      "En conclusión, la ALU demuestra que la potencia real de un computador depende de la precisión con la que sus circuitos manipulan la electricidad para crear matemáticas.",
    ],
  },
  {
    id: 4,
    name: "Guion sobre Direccionamiento y Operandos",
    contenido: [
      "Bienvenidos. Hoy desglosaremos cómo el diseño de las instrucciones máquina define el flujo de datos, tomando como ejemplo la suma de 5 + 3.",
      "Cada esquema determina dónde se encuentran los datos: la arquitectura de Pila no usa operandos explícitos y tarda 5 ciclos de CPU.",
      "Por otro lado, el Acumulador usa un solo operando y es la opción menos eficiente aquí, con 3 accesos a memoria y 6 ciclos.",
      "En contraste, las máquinas de Registros (como R1, R2, R3) son las más veloces, completando la operación en solo 3 ciclos de CPU.",
      "Para localizar la información usamos modos de direccionamiento. El Inmediato coloca el valor directamente en la instrucción, siendo el más rápido.",
      "El direccionamiento Directo apunta a una dirección fija, mientras que el Indirecto emplea registros como punteros hacia la RAM.",
      "También es vital el direccionamiento Indexado, que suma un valor base a un registro para recorrer tablas de datos eficientemente.",
      "Arquitecturas como ARM priorizan registros puros (R0-R31), mientras que x86 usa un esquema mixto para asegurar la compatibilidad.",
      "Como conclusión, el diseño de instrucciones busca reducir los ciclos de CPU minimizando los accesos lentos a la memoria externa.",
    ],
  },
  {
    id: 5,
    name: "Guion sobre RISC vs CISC",
    contenido: [
      "Hablemos de las dos grandes filosofías que dominan el mundo de los procesadores: RISC y CISC, analizando su desempeño en el procesamiento de imagen.",
      "RISC apuesta por instrucciones simples que alcanzan un IPC de 1 (una instrucción por ciclo) y un consumo bajísimo de solo 5W.",
      "CISC utiliza instrucciones complejas que ahorran código, pero su hardware es tan denso que baja el IPC a 0.5 y dispara el consumo a 50W.",
      "Si observamos el diagrama, para procesar un píxel, RISC necesita 5 ciclos de CPU mientras que CISC requiere 10 debido a su complejidad interna.",
      "Los procesadores modernos de Intel son 'CISC por fuera', pero internamente traducen todo a microoperaciones (Micro-ops) de estilo RISC.",
      "En términos de eficiencia, RISC es el rey de los móviles (Cortex-A72) porque prioriza la velocidad por ciclo y el ahorro de batería.",
      "CISC sigue siendo la opción preferida en servidores donde la potencia bruta justifica el mayor gasto energético.",
      "Al final, la industria ha convergido en un modelo híbrido: la programabilidad del CISC con la ejecución atómica del RISC.",
    ],
  },
  {
    id: 6,
    name: "Guion sobre la Unidad de Control",
    contenido: [
      "Entramos de lleno en la Unidad de Control, el componente crítico que coordina cada movimiento interno mediante señales eléctricas.",
      "Existen dos formas principales de implementarla: el Control Cableado (típico de RISC) y el Control Microprogramado (típico de CISC).",
      "El control cableado usa puertas lógicas directas; es increíblemente rápido (casi 1 ciclo por instrucción) pero es un hardware rígido.",
      "Por su parte, el control microprogramado utiliza una 'Control Store' o memoria interna, lo que hace al procesador flexible y actualizable.",
      "Como muestra la comparativa de rendimiento, el microprogramado requiere más ciclos por instrucción debido al acceso a su propia memoria.",
      "Un punto clave hoy en día es la seguridad: fallos como Spectre pueden corregirse actualizando el microcódigo sin tener que cambiar el chip.",
      "Gracias a esta actualización, la Unidad de Control aprende una nueva secuencia de pasos para ejecutar instrucciones de forma segura.",
      "En definitiva, la Unidad de Control es el puente que permite que el software abstracto se convierta en acciones físicas reales.",
    ],
  },
];
